### ISSUE TITLE
NoSuchMethodError from F-Droid

### ISSUE THREAD

**Issue by Findus23** [wuan/bo-android#184]
Hi,

I just saw your app on F-Droid and it looks quite interesting.

Unfortunatly it does crash on start for me with the following error (maybe related to #182)
java.lang.NoSuchMethodError: No virtual method setMinZoomLevel(Ljava/lang/Double;)V in class Lorg/blitzortung/android/map/OwnMapView

Logcat:
```
02-06 18:16:15.651  1022 14309 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.blitzortung.android.app/.Main bnds=[35,861][287,1152]} from uid 10010
02-06 18:16:15.674   513 31388 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0x7f
02-06 18:16:15.688  1022 14309 I ActivityManager: Start proc 31323:org.blitzortung.android.app/u0a92 for activity org.blitzortung.android.app/.Main
02-06 18:16:15.783 31323 31323 E BO_ANDROID: JsonRpcDataProvider.tocheckedUrl() invalid
02-06 18:16:15.785 31323 31323 V BO_ANDROID: JsonRpcDataProvider(https://bo-service.tryb.de/)
02-06 18:16:15.785 31323 31323 D BO_ANDROID: DataHandler.updateData() disabled
02-06 18:16:15.785 31323 31323 I chatty  : uid=10092(org.blitzortung.android.app) identical 3 lines
02-06 18:16:15.785 31323 31323 D BO_ANDROID: DataHandler.updateData() disabled
02-06 18:16:15.788 31323 31323 V BO_ANDROID: LocationHandler.enableProvider(network)
02-06 18:16:15.788 31323 31323 D BO_ANDROID: Tried to start provider 'network' without permission granted
02-06 18:16:15.797 31323 31323 D BO_ANDROID: AlertHandler() create org.blitzortung.android.alert.handler.AlertHandler@8c5d09c
02-06 18:16:15.798 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() alertEnabled = true
02-06 18:16:15.798 31323 31323 V BO_ANDROID: AlertHandler.refresh() enable updates
02-06 18:16:15.799 31323 31323 D BO_ANDROID: Tried to start provider 'network' without permission granted
02-06 18:16:15.799 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() measurementSystem = METRIC
02-06 18:16:15.799 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() notificationDistanceLimit = 50.0
02-06 18:16:15.799 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() signalingDistanceLimit = 25.0
02-06 18:16:15.799 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() signalingThresholdTime = 0
02-06 18:16:15.799 31323 31323 V BO_ANDROID: AlertHandler.onSharedPreferenceChanged() vibrationDuration = 30
02-06 18:16:15.846 31323 31323 V BO_ANDROID: Main.onCreate()
02-06 18:16:15.848 31323 31323 D BO_ANDROID: updateVersionStatus() name=org.blitzortung.android.app, state=NO_UPDATE, configuredVersion=217, currentVersion=217
02-06 18:16:15.871 31323 31323 I OsmDroid: Using tile source: Mapnik
02-06 18:16:15.878 31323 31344 E OsmDroid: unable to create a nomedia file. downloaded tiles may be visible to the gallery. Permission denied
02-06 18:16:15.880 31323 31323 I OsmDroid: sdcard state: mounted
02-06 18:16:15.885 31323 31323 I chatty  : uid=10092(org.blitzortung.android.app) identical 1 line
02-06 18:16:15.889 31323 31323 I OsmDroid: sdcard state: mounted
02-06 18:16:15.910 31323 31323 D AndroidRuntime: Shutting down VM
02-06 18:16:15.910 31323 31323 E AndroidRuntime: FATAL EXCEPTION: main
02-06 18:16:15.910 31323 31323 E AndroidRuntime: Process: org.blitzortung.android.app, PID: 31323
02-06 18:16:15.910 31323 31323 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setMinZoomLevel(Ljava/lang/Double;)V in class Lorg/blitzortung/android/map/OwnMapView; or its super classes (declaration of 'org.blitzortung.android.map.OwnMapView' appears in /data/app/org.blitzortung.android.app-6_WgUBlYFscYv_RPXY1K4g==/base.apk)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at org.blitzortung.android.map.OwnMapView.<init>(OwnMapView.kt:52)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at org.blitzortung.android.map.MapFragment.onCreateView(MapFragment.kt:35)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at org.blitzortung.android.app.Main.onStart(Main.kt:324)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7029)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-06 18:16:15.910 31323 31323 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-06 18:16:15.912  1022  8630 W ActivityManager:   Force finishing activity org.blitzortung.android.app/.Main
02-06 18:16:15.920  1022  1085 I ActivityManager: Showing crash dialog for package org.blitzortung.android.app u0
02-06 18:16:16.279  4398  7186 V AutoUpdateManager: check auto upload tasks, 0 in queue
02-06 18:16:16.415  1022  1084 W ActivityManager: Activity pause timeout for ActivityRecord{3125bc5 u0 org.blitzortung.android.app/.Main t6611 f}
02-06 18:16:16.444  1022  1032 I zygote64: Background concurrent copying GC freed 92716(16MB) AllocSpace objects, 31(688KB) LOS objects, 42% free, 22MB/39MB, paused 194us total 119.614ms
02-06 18:16:17.013  3313  3403 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

**About my device:**
Android 8.1.0
LineageOS 15.1
(microg fork)
no play services, just microg
app version 2.0.2 (from f-droid)

If you need more details, just ask.

**Comment by wuan** [comment]
Please have a look at the new 2.0.3 (223) which should become available soon.

**Comment by gdt** [comment]
As a data point, version 2.0.3 (223) from f-droid, just added today, installs and works fine under lineage 15.1 (android 8.1).  Earlier versions from f-droid had failed to install (with an error from the OS install screen).  So thanks for whatever you did to fix.

**Comment by Findus23** [comment]
223 from f-droid also works for me.

Many thanks for looking into this!
